spring.datasource.url=jdbc:postgresql://dpg-d7e8bv9j2pic7382d7bg-a.oregon-postgres.render.com/dbfirst_lvkf?sslmode=require
spring.datasource.username=dbfirst_lvkf_user
spring.datasource.password=v6X7kaFOYMgWHhrIpTlTykwRhVZVt3PA
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=selvasumma5@gmail.com
spring.mail.password=mljh meql zaes qhjx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
